spring:
  datasource:
    username: root
    password: "000802"
    url: jdbc:mysql://localhost:3306/debate?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis:
  #type-aliases-package:com.example.demo.pojo
  #mapper-locations:classpath:mapper/*.xml
mybatis:
  type-aliases-package: com.example.demo.pojo
  mapper-locations: classpath:mapper/*.xml
